name: Generate github stage tag version ☕

on:
  push:
    branches: [stage]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '--release')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing Composer dependencies ⬇️
        run: composer install --prefer-dist --no-progress

      - name: Installing Node dependencies ⬇️
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Building node dependencies 🧱
        run: yarn build

      - name: Removing cache folder 🗑️
        run: |
          rm -r -f .parcel-cache/

      - name: Removing git files 🗑️
        run: |
          rm -f .gitignore

      - name: Creating a new GitHub tag 🤖
        run: |
          TAG_VERSION=$(bash .github/tag.sh)

          git config --global user.email "matheus@aguia.dev"
          git config --global user.name "Matheus Aguiar"

          git add .
          git commit -am "build: Building a new developer version"

          git tag -a v$TAG_VERSION-dev -m "New developer tag: v$TAG_VERSION-dev"
          git push origin v$TAG_VERSION-dev

          echo "All right! 🍕"