name: Generate new plugin tag version ☕

on:
  push:
    branches: [master]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '--release')"
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing Composer dependencies ⬇️
        run: composer install --prefer-dist --no-progress

      - name: Installing Node dependencies ⬇️
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Building node dependencies 🧱
        run: yarn build

      - name: Removing development folders 🗑️
        run: |
          rm -r -f build/
          rm -r -f node_modules/
          rm -r -f .vscode/
          rm -r -f .parcel-cache/
          rm -r -f .idea/
          rm -r -f tests/
          rm -r -f assets/scripts/
          rm -r -f assets/styles/

      - name: Removing development files 🗑️
        run: |
          rm -f composer.json
          rm -f composer.lock
          rm -f package.json
          rm -f package-json.lock
          rm -f yarn.lock
          rm -f README.md
          rm -f .gitignore
          rm -f tailwind.config.js

      - name: Creating a new GitHub branch release 🤖
        run: |
          TAG_VERSION=$(bash .github/tag.sh)

          git checkout -b build/branch_release_v$TAG_VERSION

          git config --global user.email "matheus@aguia.dev"
          git config --global user.name "Matheus Aguiar"

          git add .
          git commit -am "build: building a new version"

          git push origin build/branch_release_v$TAG_VERSION

          echo "All right! 🍕"