name: Deploy to WordPress.org 🌐
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          rm -r -f .github/
          rm -r -f .git/

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{secrets.SVN_PASSWORD}}
          SVN_USERNAME: ${{secrets.SVN_USERNAME}}
          SOURCE_DIR: /
          SLUG: wc-payment-links
          ASSETS_DIR: assets
